### ISSUE TITLE
Feature: Change all text simultaneously

### ISSUE THREAD

**Issue by rockettown1** [rockettown1/gfont-clone-challenge#1]
When you start typing in one of the text boxes, a button should appear which allows you to apply the text you type to every box.

See the google font's website for a working example:

![apply-button](https://user-images.githubusercontent.com/48166152/74722429-d09bca00-5230-11ea-8093-918155679d7c.png)

**Comment by natmarek** [comment]
Button added, changes now applicable to all text areas.
