### ISSUE TITLE
Red plus icons should only be able to control their own font information.

### ISSUE THREAD

**Issue by rockettown1** [rockettown1/gfont-clone-challenge#18]
When you click on a red icon, it should only be able to toggle it's own font information on the screen.

Current situation:
If you click the icon on one font - it will show the css information for that font.
If you then click the icon on a different font - it will close the css information for the previous font.

From a user's point of view - when the red icon is clicked it should show the CSS info for that font (and that is it's only job)

**Comment by natmarek** [comment]
Issue fixed.
