### ISSUE TITLE
Feature: Showing CSS information

### ISSUE THREAD

**Issue by rockettown1** [rockettown1/gfont-clone-challenge#2]
When you click on the red plus symbol, a box should appear from the bottom with the following CSS information:

The import statement to add the font to a CSS file, and the font family information.
eg:

@import url('https://fonts.googleapis.com/css?family=Roboto&display=swap');
font-family: 'Roboto', sans-serif;

**This information is available from the Google fonts website.**

You can style it however you want, as long as it contains the correct information for each font.

**Comment by natmarek** [comment]
Issue resolved. Information added.
